apiVersion: v1
kind: Namespace
metadata:
  name: e2e-tests
  labels:
    name: e2e-tests
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring-prometheus
  labels:
    name: monitoring-prometheus