apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushgateway
  namespace: monitoring-prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      pushgateway: web
  template:
    metadata:
      labels:
        pushgateway: web
    spec:
      containers:
        - name: pushgateway
          image: prom/pushgateway
---
apiVersion: v1
kind: Service
metadata:
  name: pushgateway
  namespace: monitoring-prometheus
spec:
  type: NodePort
  selector:
    pushgateway: web
  ports:
    - port: 9091
      targetPort: 9091
      nodePort: 30003