apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: job
  namespace: e2e-tests
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cypress-test-local
              image: cypress-test-image:1.0.0
              # We are pulling the image locally
              imagePullPolicy: Never

#            - name: cypress-test
#                image: cypress-test-image:latest
          restartPolicy: OnFailure